### ISSUE TITLE
[Solr] Libs are not loaded.

### ISSUE THREAD

**Issue by churel** [hence-io/images#1]
When we start the image we have this two Warning messages : 

```
Invalid Date Invalid Date4596 [coreLoadExecutor-5-thread-1] WARN  org.apache.solr.core.SolrResourceLoader  [   ] – Can't find (or read) directory to add to classloader: ../../../contrib/extraction/lib (resolved as: /opt/solr/server/solr/drupal/../../../contrib/extraction/lib).
Invalid Date Invalid Date4597 [coreLoadExecutor-5-thread-1] WARN  org.apache.solr.core.SolrResourceLoader  [   ] – Can't find (or read) directory to add to classloader: ../../../contrib/clustering/lib/ (resolved as: /opt/solr/server/solr/drupal/../../../contrib/clustering/lib).
```

If you change the path in the solrconfig.xml to the full path : 

```
<lib dir="/opt/solr-5.2.1/contrib/extraction/lib" />
<lib dir="/opt/solr-5.2.1/contrib/clustering/lib/" />
```

It's working.
Don't know exactly what is the issue but seems to be the simlink.

**Comment by ghost** [comment]
Resolved by using absolute paths in solrconfig.xml file, as otherwise, we would need to copy the directories instead of symlinking, which slows down container startup, and causes container startups to fail if the copy isn't finished when solr tries to start. 

This start failure would likely be mitigated by an arbitrary timeout, but this theoretically could still fail, and would cause an unnecessary slowdown in startup times.
